### ISSUE TITLE
HHsearch Error and missing process files

### ISSUE THREAD

**Issue by zxx666666** [steineggerlab/foldseek#277]
- 21:14:41.031 ERROR: In /opt/conda/conda-bld/hhsuite_1709621322429/work/src/hhdatabase.cpp:443: getTemplateHMM:

- 21:14:41.031 ERROR: 	Unrecognized HMM file format in '6zyw_B'.

- 21:14:41.031 ERROR: 	Context:
'

- 21:14:41.031 ERROR: 

- 21:14:41.031 ERROR: '

Error executing job with overrides: []
Traceback (most recent call last):
  File "/home/xml/tools/RosettaFold/RoseTTAFold-All-Atom/rf2aa/run_inference.py", line 206, in main
    runner.infer()
  File "/home/xml/tools/RosettaFold/RoseTTAFold-All-Atom/rf2aa/run_inference.py", line 153, in infer
    self.parse_inference_config()
  File "/home/xml/tools/RosettaFold/RoseTTAFold-All-Atom/rf2aa/run_inference.py", line 46, in parse_inference_config
    protein_input = generate_msa_and_load_protein(
  File "/home/xml/tools/RosettaFold/RoseTTAFold-All-Atom/rf2aa/data/protein.py", line 93, in generate_msa_and_load_protein
    return load_protein(str(msa_file), str(hhr_file), str(atab_file), model_runner)
  File "/home/xml/tools/RosettaFold/RoseTTAFold-All-Atom/rf2aa/data/protein.py", line 66, in load_protein
    xyz_t, t1d, mask_t, _ = get_templates(
  File "/home/xml/tools/RosettaFold/RoseTTAFold-All-Atom/rf2aa/data/protein.py", line 30, in get_templates
    ) = parse_templates_raw(ffdb, hhr_fn=hhr_fn, atab_fn=atab_fn)
  File "/home/xml/tools/RosettaFold/RoseTTAFold-All-Atom/rf2aa/data/parsers.py", line 628, in parse_templates_raw
    for l in open(atab_fn, "r").readlines():
FileNotFoundError: [Errno 2] No such file or directory: '7qxr/A/t000_.atab'

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

**Comment by martin-steinegger** [comment]
Sorry this is not the correct repository. Please open it here: https://github.com/soedinglab/hh-suite
