### ISSUE TITLE
easy-search problem - paniced

### ISSUE THREAD

**Issue by christophista** [steineggerlab/foldseek#348]
Hello

I am trying to run the example from the github repo (file 8tim.pdb) and search it against the bfvd database from 
https://bfvd.steineggerlab.workers.dev/. 
However, easy-search crashed with the below message. 
Is there anything wrong with the invocation? How can I get rid of the crash? 

Thank you in advance!

The command to invoke foldseek easy-search is
```
foldseek easy-search \
    --format-mode 4 \
    --format-output query,target,fident,alnlen,mismatch,qstart,qend,tstart,tend,evalue \
    "$INPUT_STRUCTURE" \
    "$FOLDSEEK_DB" \
    "$EASYSEARCH_OUTPUT" \
    "$TMP_DIR"
```
with
```
INPUT_STRUCTURE  : 'input/8tim.pdb'
FOLDSEEK_DB      : '/nfs/scistore14/rcsb/BFVD4Foldseek/bfvd'
EASYSEARCH_OUTPUT: 'output/8tim_easysearch_BFVD.tsv'
TMP_DIR          : '/tmp/23153914'
```
and the DB files: 
```
-rw-r--r-- 1 388M Sep  6 14:56 /nfs/scistore14/rcsb/BFVD4Foldseek/bfvd
-rw-r--r-- 1 4 Sep  6 08:26 /nfs/scistore14/rcsb/BFVD4Foldseek/bfvd.dbtype
-rw-r--r-- 1 6.4M Sep  6 08:26 /nfs/scistore14/rcsb/BFVD4Foldseek/bfvd.index
-rw-r--r-- 1 42M Sep  6 08:26 /nfs/scistore14/rcsb/BFVD4Foldseek/bfvd.lookup
-rw-r--r-- 1 24M Sep  6 08:26 /nfs/scistore14/rcsb/BFVD4Foldseek/bfvd.source
-rw-r--r-- 1 8.6G Sep 11 13:58 /nfs/scistore14/rcsb/BFVD4Foldseek/bfvd.tar.gz
-rw-r--r-- 1 8 Sep 11 14:06 /nfs/scistore14/rcsb/BFVD4Foldseek/bfvd.version
-rw-r--r-- 1 384M Sep  6 08:26 /nfs/scistore14/rcsb/BFVD4Foldseek/bfvd_ca
-rw-r--r-- 1 4 Sep  6 08:26 /nfs/scistore14/rcsb/BFVD4Foldseek/bfvd_ca.dbtype
-rw-r--r-- 1 6.9M Sep  6 08:26 /nfs/scistore14/rcsb/BFVD4Foldseek/bfvd_ca.index
-rw-r--r-- 1 772M Sep 11 14:08 /nfs/scistore14/rcsb/BFVD4Foldseek/bfvd_foldcompdb.tar.gz
-rw-r--r-- 1 536M Sep 11 14:08 /nfs/scistore14/rcsb/BFVD4Foldseek/bfvd_foldseekdb.tar.gz
-rw-r--r-- 1 58M Sep  6 08:26 /nfs/scistore14/rcsb/BFVD4Foldseek/bfvd_h
-rw-r--r-- 1 4 Sep  6 08:26 /nfs/scistore14/rcsb/BFVD4Foldseek/bfvd_h.dbtype
-rw-r--r-- 1 6.5M Sep  6 08:26 /nfs/scistore14/rcsb/BFVD4Foldseek/bfvd_h.index
-rw-r--r-- 1 4.9M Sep  8 09:06 /nfs/scistore14/rcsb/BFVD4Foldseek/bfvd_mapping
-rw-r--r-- 1 32M Sep 11 14:10 /nfs/scistore14/rcsb/BFVD4Foldseek/bfvd_metadata.tsv
-rw-r--r-- 1 65M Sep  6 08:26 /nfs/scistore14/rcsb/BFVD4Foldseek/bfvd_ss
-rw-r--r-- 1 4 Sep  6 08:26 /nfs/scistore14/rcsb/BFVD4Foldseek/bfvd_ss.dbtype
-rw-r--r-- 1 6.4M Sep  6 08:26 /nfs/scistore14/rcsb/BFVD4Foldseek/bfvd_ss.index
-rw-r--r-- 1 25M Sep 11 14:10 /nfs/scistore14/rcsb/BFVD4Foldseek/bfvd_taxId.tsv
-rw-r--r-- 1 687M Sep  8 09:06 /nfs/scistore14/rcsb/BFVD4Foldseek/bfvd_taxonomy
```

Error is: 
```
4170.022267 k-mers per position
5917198 DB matches per sequence
2 overflows
1000 sequences passed prefiltering per query sequence
1000 median result list length
0 sequences with 0 size result lists
Time for merging to pref: 0h 0m 0s 0ms
Time for processing: 0h 0m 14s 213ms
thread '<unnamed>' panicked at ../src/scores.rs:130:9:
assertion failed: c >= b\'A\' && c <= Self::NULL
stack backtrace:
structurealign /tmp/23153855/10753808693940151180/query /nfs/scistore14/rcsb/BFVD4Foldseek/bfvd /tmp/23153855/10753808693940151180/search_tmp/8279189473187317920/pref /tmp/23153855/10753808693940151180/search_tmp/8279189473187317920/strualn --tmscore-threshold 0 --lddt-threshold 0 --sort-by-structure-bits 1 --alignment-type 2 --sub-mat 'aa:3di.out,nucl:3di.out' -a 0 --alignment-mode 3 --alignment-output-mode 0 --wrapped-scoring 0 -e 10 --min-seq-id 0 --min-aln-len 0 --seq-id-mode 0 --alt-ali 0 -c 0 --cov-mode 0 --max-seq-len 65535 --comp-bias-corr 1 --comp-bias-corr-scale 0.5 --max-rejected 2147483647 --max-accept 2147483647 --add-self-matches 0 --db-load-mode 0 --pca substitution:1.100,context:1.400 --pcb substitution:4.100,context:5.800 --score-bias 0 --realign 0 --realign-score-bias -0.2 --realign-max-seqs 2147483647 --corr-score-weight 0 --gap-open aa:10,nucl:10 --gap-extend aa:1,nucl:1 --zdrop 40 --threads 384 --compressed 0 -v 3 

[=================================================================thread '<unnamed>' panicked at ../src/scores.rs:130:9:
assertion failed: c >= b\'A\' && c <= Self::NULL
   0: rust_begin_unwind
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:595:5
   1: core::panicking::panic_fmt
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/panicking.rs:67:14
   2: core::panicking::panic
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/panicking.rs:117:5
   3: block_aligner_c::scan_block::PaddedBytes::set_bytes
   4: _ZN22StructureSmithWaterman27alignStartPosBacktraceBlockEPKhS1_ihhRNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_7s_alignE
             at /home/vsts/work/1/s/src/commons/StructureSmithWaterman.cpp:368:30
   5: _Z14alignStructureR22StructureSmithWatermanS0_R8SequenceS2_jjR15EvalueNeuralNetSt4pairIddERN7Matcher8result_tERNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEER10Parameters
             at /home/vsts/work/1/s/src/strucclustutils/structurealign.cpp:78:102
   6: _Z14structurealigniPPKcRK7Command._omp_fn.0
             at /home/vsts/work/1/s/src/strucclustutils/structurealign.cpp:368:38
   7: gomp_thread_start
   8: start_thread
             at /build/glibc-BHL3KM/glibc-2.31/nptl/pthread_create.c:477:8
   9: clone
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: rust_begin_unwind
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:595:5
   1: core::panicking::panic_fmt
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/panicking.rs:67:14
   2: core::panicking::panic
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/panicking.rs:117:5
   3: block_aligner_c::scan_block::PaddedBytes::set_bytes
   4: _ZN22StructureSmithWaterman27alignStartPosBacktraceBlockEPKhS1_ihhRNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_7s_alignE
             at /home/vsts/work/1/s/src/commons/StructureSmithWaterman.cpp:368:30
   5: _Z14alignStructureR22StructureSmithWatermanS0_R8SequenceS2_jjR15EvalueNeuralNetSt4pairIddERN7Matcher8result_tERNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEER10Parameters
             at /home/vsts/work/1/s/src/strucclustutils/structurealign.cpp:78:102
   6: _Z14structurealigniPPKcRK7Command._omp_fn.0
             at /home/vsts/work/1/s/src/strucclustutils/structurealign.cpp:368:38
   7: gomp_thread_start
   8: start_thread
             at /build/glibc-BHL3KM/glibc-2.31/nptl/pthread_create.c:477:8
   9: clone
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Aborted
Error: Structure alignment step died
Error: Search died
Error: Foldseek easy-search failed.
```

**Comment by martin-steinegger** [comment]
I can not reproduce this issue on the newest version. Did you try updating foldseek?
